######################## default configuration ####################
baseURL = "https://elvisfinol.github.io/lourdesmagni-portfolio/"
languageCode = "en-us"
title = "Lourdes Magni"
theme = "influencer-hugo"
summaryLength = "10"
paginate = 6

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  baseURL = "https://use.fontawesome.com/releases/v5.15.2/css/all.css"
  [[params.plugins.css]]
  URL = "plugins/fontawesome-free-5.15.2-web/fontawesome.min"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/magnific-popup.css"
  
  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/magnific-popup.min.js"

  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "Sobre Mí"
  URL = "author"
  weight = 1
  
  # [[menu.main]]
  # name = "Chapter"
  # URL = "chapter"
  # weight = 2

  [[menu.main]]
  name = "Servicios"
  URL = "service"
  weight = 2
  
  [[menu.main]]
  name = "Testimonios"
  URL = "review"
  weight = 3
  
  # [[menu.main]]
  # name = "Author"
  # URL = "author"
  # weight = 4
  
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 4

  [[menu.main]]
  name = "Talleres"
  URL = "talleres"
  weight = 5

  [[menu.main]]
  name = "Prensa"
  URL = "prensa"
  weight = 6


#################### default parameters ################################
[params]
logo = ""
home = "Home"
# Meta data
description = "This is meta description"
author = "Lourdes Magni"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# copyright
copyright = "Copyright &copy; 2021 [Elvis Finol](https://elvisfinol.com) All Rights Reserved"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.navButton]
enable = true

# cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# Footer ########################
[params.footer]
content = "Each theme featured at the Bootstrap marketplace has been reviewed by Bootstrap's creators.Lorem ipsum dolor sit amet, consectetur adipisicing elit."


############################# post share ###################
[[params.share]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.share]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.share]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.share]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"